import React, { useEffect, useMemo, useRef, useState } from 'react'
import * as XLSX from 'xlsx'
import { useAuth } from './auth/AuthGate'
import { isSharedDataMode } from './config/runtime'
import { createMigrationRepository } from './data/migrationRepository'
import {
  AlertTriangle, ArrowRight, BarChart3, Bell, Building2, Check, CheckCircle2,
  ChevronDown, ChevronRight, Clock3, CloudCog, FileSpreadsheet, Gauge,
  LayoutDashboard, ListChecks, Menu, Network, Plus, Search, Settings, Upload,
  UserRound, Users, X
} from 'lucide-react'

const STAGES = ['Identified','Partner Preparation','Account Preparation','Technical Migration Requested','Migration In Progress','Validation','Completed']
const OWNERS = ['Clint','Lance','Glen','Janey','Matt']

const demo = [
  {id:'demo-1',partner:'Northstar IT Services',owner:'Clint',stage:'Account Preparation',waitOn:'Dolos',target:'2026-08-28',last:'2026-08-24',wg:'ACC-3000001',buyIn:true,login:true,nfr:'Activated',alias:true,operator:true,notes:'Creating WatchGuard subscriber accounts.',accounts:[
    {id:'a1',name:'Blue Harbor Foods',panda:'83111001',product:'Endpoint Security',licenses:18,wg:'WGC-2-DEMO001'},
    {id:'a2',name:'Oakline Logistics',panda:'83111002',product:'Endpoint Security',licenses:26,wg:'WGC-2-DEMO002'},
    {id:'a3',name:'Redwood Trading',panda:'83111003',product:'Fusion',licenses:12,wg:''}
  ]},
  {id:'demo-2',partner:'Cape Meridian Systems',owner:'Lance',stage:'Partner Preparation',waitOn:'Customer',target:'2026-09-04',last:'2026-08-18',wg:'',buyIn:true,login:false,nfr:'Not Requested',alias:false,operator:false,notes:'Waiting for partner to complete WatchGuard account mapping.',accounts:[]},
  {id:'demo-3',partner:'Harbourline Technology',owner:'Glen',stage:'Technical Migration Requested',waitOn:'WatchGuard',target:'2026-08-29',last:'2026-08-19',wg:'ACC-3000003',buyIn:true,login:true,nfr:'Activated',alias:true,operator:true,notes:'Migration template submitted.',accounts:[{id:'h1',name:'Fictional Client One',panda:'83112001',product:'Endpoint Security',licenses:30,wg:'WGC-2-DEMO101'}]},
  {id:'demo-4',partner:'Greenstone Networks',owner:'Janey',stage:'Migration In Progress',waitOn:'WatchGuard',target:'2026-08-24',last:'2026-08-20',wg:'ACC-3000004',buyIn:true,login:true,nfr:'Activated',alias:true,operator:true,notes:'Migration in progress.',accounts:[{id:'g1',name:'Fictional Group A',panda:'83113001',product:'Fusion',licenses:41,wg:'WGC-2-DEMO201'}]},
  {id:'demo-5',partner:'Summit MSP',owner:'Matt',stage:'Validation',waitOn:'Dolos',target:'2026-08-27',last:'2026-08-25',wg:'ACC-3000005',buyIn:true,login:true,nfr:'Activated',alias:true,operator:true,notes:'Validation outstanding.',accounts:[{id:'s1',name:'Demo Retail',panda:'83114001',product:'Endpoint Security',licenses:24,wg:'WGC-2-DEMO301'}]},
  {id:'demo-6',partner:'Blue Crane IT',owner:'Clint',stage:'Completed',waitOn:'None',target:'2026-08-14',last:'2026-08-13',wg:'ACC-3000006',buyIn:true,login:true,nfr:'Activated',alias:true,operator:true,notes:'Validated and closed.',accounts:[{id:'b1',name:'Demo Customer A',panda:'83115001',product:'Endpoint Security',licenses:15,wg:'WGC-2-DEMO401'}]}
]

const today = () => new Date(new Date().toISOString().slice(0,10)+'T12:00:00')
const dayDiff = d => d ? Math.floor((new Date(d+'T12:00:00')-today())/86400000) : null
const elapsed = d => d ? Math.max(0,Math.floor((today()-new Date(d+'T12:00:00'))/86400000)) : 0
const uid = () => Date.now().toString(36)+Math.random().toString(36).slice(2,8)

function status(m){ if(m.stage==='Completed') return 'Completed'; if(m.blocker) return 'Blocked'; if(dayDiff(m.target)<0) return 'Overdue'; if(m.waitOn==='Customer') return 'Waiting on Customer'; if(m.waitOn==='WatchGuard') return 'Waiting on WatchGuard'; return 'On Track' }
function acct(m){const total=m.accounts?.length||0, ready=(m.accounts||[]).filter(a=>a.wg).length; return {total,ready,pct:total?Math.round(ready/total*100):0}}
function readiness(m){const p=acct(m); const checks=[['Partner buy-in',!!m.buyIn],['Partner Panda ID',!!m.partnerPandaId],['WatchGuard SP account',!!m.wg],['WatchGuard login tested',!!m.login],['NFR activated',m.nfr==='Activated'],['Dolos alias created',!!m.alias],['Dolos operator created',!!m.operator],['Customer WG accounts',p.total>0&&p.ready===p.total]]; return {checks,score:Math.round(checks.filter(x=>x[1]).length/checks.length*100),ready:checks.every(x=>x[1])}}

function Pill({value}){const c=value==='Overdue'?'red':value==='Blocked'||value==='Waiting on WatchGuard'?'purple':value==='Waiting on Customer'?'amber':'green'; return <span className={'pill '+c}>{value}</span>}
function Progress({value}){return <div className="track"><i style={{width:value+'%'}} /></div>}
function Logo(){return <div className="logo"><i/><i/><i/></div>}

function Dashboard({data,open,newMigration}){
  const s=data.map(status), active=data.filter(m=>m.stage!=='Completed')
  const k=[['Total migrations',data.length,Gauge],['Completed',s.filter(x=>x==='Completed').length,CheckCircle2],['Active',active.length,BarChart3],['Waiting on WatchGuard',s.filter(x=>x==='Waiting on WatchGuard').length,CloudCog],['Waiting on customer',s.filter(x=>x==='Waiting on Customer').length,Users],['Blocked',s.filter(x=>x==='Blocked').length,AlertTriangle],['Overdue',s.filter(x=>x==='Overdue').length,Clock3],['Due this week',active.filter(m=>dayDiff(m.target)>=0&&dayDiff(m.target)<=7).length,Bell]]
  const exceptions=active.filter(m=>status(m)!=='On Track'||elapsed(m.last)>=5||acct(m).ready<acct(m).total).slice(0,6)
  return <div className="stack">
    <div className="heading"><div><small>OPERATIONS OVERVIEW</small><h1>Dashboard</h1></div><button className="primary" onClick={newMigration}><Plus size={16}/> New migration</button></div>
    <div className="kpis">{k.map(([label,value,I])=><div className="kpi" key={label}><span><I size={18}/></span><b>{value}</b><small>{label}</small></div>)}</div>
    <div className="two">
      <section className="panel"><div className="panelHead"><div><small>EXCEPTIONS FIRST</small><h2>Attention required</h2></div></div>{exceptions.map(m=><button className="exception" key={m.id} onClick={()=>open(m.id)}><i className={'dot '+(status(m)==='Overdue'?'red':status(m)==='Waiting on WatchGuard'?'purple':'amber')}/><div><b>{m.partner}</b><small>{status(m)==='On Track'?`${acct(m).total-acct(m).ready} customer accounts need WG IDs`:status(m)} · {elapsed(m.last)} days since activity</small></div><span>{m.owner}</span><ChevronRight size={16}/></button>)}</section>
      <section className="panel"><div className="panelHead"><div><small>TEAM</small><h2>Workload by owner</h2></div></div>{OWNERS.map(o=>{const n=active.filter(m=>m.owner===o).length;return <div className="owner" key={o}><span>{o[0]}</span><div><b>{o}<em>{n} active</em></b><Progress value={Math.min(100,n*18)}/></div></div>})}</section>
    </div>
    <section className="panel"><div className="panelHead"><div><small>CURRENT FLOW</small><h2>Migration pipeline</h2></div></div><div className="pipeline">{STAGES.map(x=><div key={x}><b>{data.filter(m=>m.stage===x).length}</b><small>{x}</small><i/></div>)}</div></section>
    <section className="panel tablePanel"><div className="panelHead pad"><div><small>NEXT DEADLINES</small><h2>Active migrations</h2></div></div><Table data={active} open={open}/></section>
  </div>
}

function Table({data,open}){return <div className="scroll"><table><thead><tr><th>Partner</th><th>Stage</th><th>Status</th><th>Owner</th><th>Accounts</th><th>Target</th><th/></tr></thead><tbody>{data.map(m=><tr key={m.id} onClick={()=>open(m.id)}><td><b>{m.partner}</b><small>{m.wg||'WG SP ID not captured'}</small></td><td>{m.stage}</td><td><Pill value={status(m)}/></td><td>{m.owner}</td><td>{acct(m).total?`${acct(m).ready}/${acct(m).total}`:'—'}</td><td className={dayDiff(m.target)<0&&m.stage!=='Completed'?'danger':''}>{m.target||'—'}</td><td><ChevronRight size={15}/></td></tr>)}</tbody></table></div>}

function Migrations({data,open,newMigration}){const [q,setQ]=useState(''); const rows=data.filter(m=>(m.partner+' '+m.owner+' '+m.stage).toLowerCase().includes(q.toLowerCase())); return <div className="stack"><div className="heading"><div><small>PARTNER MIGRATION PROJECTS</small><h1>Migrations</h1></div><button className="primary" onClick={newMigration}><Plus size={16}/> New migration</button></div><section className="panel tablePanel"><div className="toolbar"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search partner, owner or stage"/></label></div><Table data={rows} open={open}/></section></div>}

const norm=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]/g,'')
const pick=(row,names)=>{const e=Object.entries(row).find(([k])=>names.includes(norm(k)));return e?e[1]:''}
const ID_HEADERS=['pandaidentifier','pandacustomeridentifier','pandacustomerid','customeridentifier','customerid','identifier']
const NAME_HEADERS=['customer','customername','company','companyname','name','client','clientname']
function ppcSheet(wb){
  for(const name of wb.SheetNames){
    const ws=wb.Sheets[name], matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false})
    let best=-1, score=0
    matrix.slice(0,50).forEach((row,i)=>{const keys=row.map(norm), next=(keys.some(k=>ID_HEADERS.includes(k))?2:0)+(keys.some(k=>NAME_HEADERS.includes(k))?1:0);if(next>score){best=i;score=next}})
    if(score>=2)return {ws,headerRow:best}
  }
  throw Error('Could not find the Panda customer header row. Check that this is a PPC customer export.')
}
function ImportPage({data,onImport,newMigration}){
  const [migrationId,setMigrationId]=useState(data.find(m=>m.stage!=='Completed')?.id||''); const [rows,setRows]=useState([]); const [error,setError]=useState(''); const input=useRef()
  const read=file=>{if(!file)return;setError('');const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}), found=ppcSheet(wb), raw=XLSX.utils.sheet_to_json(found.ws,{range:found.headerRow,defval:'',raw:false});const parsed=raw.map(row=>({id:uid(),name:String(pick(row,NAME_HEADERS)||'').trim(),panda:String(pick(row,ID_HEADERS)||'').replace(/[{}]/g,'').trim(),product:String(pick(row,['product','productname','solution'])||'').trim(),licenses:Number(pick(row,['contractedlicenses','contractedlicences','licenses','licences','quantity','qty']))||'',globalId:String(pick(row,['globalcustomeridentifier','globalcustomerid','globalid'])||'').trim(),wg:''})).filter(x=>x.name&&x.panda);if(!parsed.length)throw Error('No customer rows detected beneath the Panda export header.');setRows(parsed)}catch(err){setError(err.message)}};r.readAsArrayBuffer(file)}
  return <div className="stack"><div className="heading"><div><small>STEP 4 · CUSTOMER ACCOUNT PREPARATION</small><h1>Import Panda customers</h1></div><button className="secondary" onClick={newMigration}><Plus size={16}/> New migration first</button></div><section className="panel import"><div><label>Partner migration</label><select value={migrationId} onChange={e=>setMigrationId(e.target.value)}><option value="">Select migration</option>{data.filter(m=>m.stage!=='Completed').map(m=><option key={m.id} value={m.id}>{m.partner}</option>)}</select></div><button className="drop" onClick={()=>input.current.click()}><Upload size={28}/><b>Choose Panda Cloud Partner Center export</b><small>.xls and .xlsx · processed locally in your browser</small></button><input hidden ref={input} type="file" accept=".xls,.xlsx" onChange={e=>read(e.target.files?.[0])}/></section>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}{rows.length>0&&<section className="panel tablePanel"><div className="panelHead pad"><div><small>IMPORT PREVIEW</small><h2>{rows.length} customer records detected</h2></div><button className="primary" disabled={!migrationId} onClick={()=>onImport(migrationId,rows)}><Check size={16}/> Import customers</button></div><div className="scroll"><table><thead><tr><th>Customer</th><th>Panda ID</th><th>Product</th><th>Licences</th><th>Global ID</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.panda}</td><td>{r.product||'—'}</td><td>{r.licenses||'—'}</td><td>{r.globalId||'—'}</td></tr>)}</tbody></table></div></section>}</div>
}

function Detail({migration,save,back}){
  const [m,setM]=useState(migration); const ready=readiness(m), p=acct(m)
  const setAccount=(id,wg)=>setM({...m,accounts:m.accounts.map(a=>a.id===id?{...a,wg}:a)})
  const exportTemplate=()=>{if(!m.wg)return alert('Capture the partner ACC number first.');if(!m.partnerPandaId)return alert('Capture the partner Panda ID first.');if(!m.accounts.length||m.accounts.some(a=>!a.wg))return alert('Every imported customer needs a WatchGuard account ID first.');const rows=[{Row:1,PandaCustomerID:m.partnerPandaId,WGCustomerType:'ServiceProvider',Parent:'',Name:m.partner,AccountId:m.wg,MigrationType:'EndpointsAndLicenses',LicensingModel:'LinkedToLicense',MigrationSimulation:'',ValidationErrors:'',Migration:'',MigrationStatus:''},...m.accounts.map((a,i)=>({Row:i+2,PandaCustomerID:a.panda,WGCustomerType:'Subscriber',Parent:m.wg,Name:a.name,AccountId:a.wg,MigrationType:'EndpointsAndLicenses',LicensingModel:'LinkedToLicense',MigrationSimulation:'',ValidationErrors:'',Migration:'',MigrationStatus:''}))];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Migration');XLSX.writeFile(wb,m.partner.replace(/[^a-z0-9]+/gi,'_')+'_Migration.xlsx')}
  return <div className="stack"><div className="heading"><button className="back" onClick={back}>← Back to migrations</button><div className="actions"><button className="secondary" onClick={exportTemplate}><FileSpreadsheet size={16}/> Generate WG template</button><button className="primary" onClick={()=>save(m)}><Check size={16}/> Save changes</button></div></div><section className="panel detailHero"><div><small>PARTNER MIGRATION</small><h1>{m.partner}</h1><div className="meta"><Pill value={status(m)}/><span>Owner · {m.owner}</span><span>Target · {m.target||'Not set'}</span><span>{m.wg||'No ACC number'}</span></div></div><div className="score"><b>{ready.score}%</b><small>MIGRATION READINESS</small><Progress value={ready.score}/></div></section>
  <section className="panel"><div className="panelHead"><div><small>WORKFLOW</small><h2>Migration stage</h2></div></div><div className="stages">{STAGES.map((s,i)=>{const cur=STAGES.indexOf(m.stage);return <button className={i<cur?'done':i===cur?'active':''} key={s} onClick={()=>setM({...m,stage:s,waitOn:s==='Completed'?'None':m.waitOn})}><i>{i<cur?<Check size={13}/>:i+1}</i><small>{s}</small></button>})}</div></section>
  <div className="two detailGrid"><section className="panel form"><div className="panelHead"><div><small>PARTNER PREPARATION</small><h2>Migration record</h2></div></div><div className="formgrid"><label>Owner<select value={m.owner} onChange={e=>setM({...m,owner:e.target.value})}>{OWNERS.map(o=><option key={o}>{o}</option>)}</select></label><label>Target completion<input type="date" value={m.target||''} onChange={e=>setM({...m,target:e.target.value})}/></label><label>Waiting on<select value={m.waitOn||'Dolos'} onChange={e=>setM({...m,waitOn:e.target.value})}><option>Dolos</option><option>Customer</option><option>WatchGuard</option><option>None</option></select></label><label>WG Service Provider Account<input value={m.wg||''} onChange={e=>setM({...m,wg:e.target.value})} placeholder="ACC-..."/></label><label>Partner Panda ID<input value={m.partnerPandaId||''} onChange={e=>setM({...m,partnerPandaId:e.target.value})} placeholder="Panda partner identifier"/></label><label>NFR status<select value={m.nfr||'Not Requested'} onChange={e=>setM({...m,nfr:e.target.value})}><option>Not Requested</option><option>Requested</option><option>Issued</option><option>Activated</option></select></label><label>Last activity<input type="date" value={m.last||''} onChange={e=>setM({...m,last:e.target.value})}/></label></div><div className="checks"><label><input type="checkbox" checked={!!m.buyIn} onChange={e=>setM({...m,buyIn:e.target.checked})}/> Partner buy-in confirmed</label><label><input type="checkbox" checked={!!m.login} onChange={e=>setM({...m,login:e.target.checked})}/> WatchGuard login verified</label><label><input type="checkbox" checked={!!m.alias} onChange={e=>setM({...m,alias:e.target.checked})}/> Dolos alias created</label><label><input type="checkbox" checked={!!m.operator} onChange={e=>setM({...m,operator:e.target.checked})}/> Dolos operator created</label></div><label>Blocker<input value={m.blocker||''} onChange={e=>setM({...m,blocker:e.target.value})} placeholder="Leave blank when not blocked"/></label><label>Notes<textarea rows="4" value={m.notes||''} onChange={e=>setM({...m,notes:e.target.value})}/></label></section>
  <section className="panel"><div className="panelHead"><div><small>GATE</small><h2>Ready to submit?</h2></div></div><div className="readyList">{ready.checks.map(([label,done])=><div className={done?'done':''} key={label}><i>{done?<Check size={14}/>:<Clock3 size={14}/>}</i><b>{label}</b></div>)}</div><div className={'readyBanner '+(ready.ready?'ok':'')}><b>{ready.ready?'READY TO SUBMIT':'NOT READY'}</b><small>{ready.ready?'All preparation checks are complete.':'Complete outstanding preparation items first.'}</small></div></section></div>
  <section className="panel tablePanel"><div className="panelHead pad"><div><small>STEP 4</small><h2>Customer account preparation</h2><p>{p.total?`${p.ready} of ${p.total} WatchGuard customer accounts ready.`:'Import the Panda customer export to begin.'}</p></div>{p.total>0&&<div className="accountPct"><b>{p.pct}%</b><Progress value={p.pct}/></div>}</div>{p.total?<div className="scroll"><table><thead><tr><th>Customer</th><th>Panda ID</th><th>Product</th><th>Licences</th><th>WatchGuard Account ID</th></tr></thead><tbody>{m.accounts.map(a=><tr key={a.id}><td><b>{a.name}</b></td><td>{a.panda}</td><td>{a.product||'—'}</td><td>{a.licenses||'—'}</td><td><input className="wginput" value={a.wg||''} onChange={e=>setAccount(a.id,e.target.value)} placeholder="WGC-..."/></td></tr>)}</tbody></table></div>:<div className="empty"><FileSpreadsheet size={34}/><b>No Panda customer list imported</b><small>Use Import Panda from the left navigation.</small></div>}</section></div>
}

function WatchTower(){return <div className="stack"><div className="heading"><div><small>FUTURE PLATFORM INTEGRATION</small><h1>WatchTower</h1></div></div><section className="panel wtHero"><div className="wtBrand"><Logo/><div><b>WATCHTOWER</b><small>DISTRIBUTOR MANAGEMENT PLATFORM</small></div></div><div><h2>Migration Hub is being built to fit into this ecosystem.</h2><p>The MVP keeps migration tracking separate while deliberately following WatchTower's visual language. The preferred end state is shared authentication and partner data, with Migration Hub becoming a first-class WatchTower module rather than a disconnected second application.</p></div></section><div className="three"><section className="panel"><Network/><h3>Phase 1 · Visual alignment</h3><p>Shared navigation language, dark left rail, red accent, compact operations UI.</p><Pill value="Completed"/></section><section className="panel"><CloudCog/><h3>Phase 2 · Data link</h3><p>Share partner and WatchGuard Account IDs and deep-link between licensing and migrations.</p><span className="pill amber">Needs source/API access</span></section><section className="panel"><CheckCircle2/><h3>Phase 3 · One platform</h3><p>Shared auth, shared partner model and Migration Insights backed by live Hub data.</p><span className="pill purple">Future</span></section></div></div>}

function NewModal({close,create}){const [f,setF]=useState({partner:'',partnerPandaId:'',owner:'Clint',target:''});const submit=e=>{e.preventDefault();if(!f.partner.trim())return;create({id:uid(),partner:f.partner.trim(),partnerPandaId:f.partnerPandaId.trim(),owner:f.owner,stage:'Identified',waitOn:'Dolos',target:f.target,last:new Date().toISOString().slice(0,10),wg:'',buyIn:false,login:false,nfr:'Not Requested',alias:false,operator:false,notes:'',accounts:[]})};return <div className="modalBg"><form className="modal" onSubmit={submit}><div className="panelHead"><div><small>NEW PARTNER MIGRATION</small><h2>Create migration</h2></div><button type="button" className="icon" onClick={close}><X size={17}/></button></div><label>Partner name<input autoFocus value={f.partner} onChange={e=>setF({...f,partner:e.target.value})}/></label><label>Partner Panda ID<input value={f.partnerPandaId} onChange={e=>setF({...f,partnerPandaId:e.target.value})}/></label><label>Owner<select value={f.owner} onChange={e=>setF({...f,owner:e.target.value})}>{OWNERS.map(o=><option key={o}>{o}</option>)}</select></label><label>Target completion<input type="date" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></label><div className="actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary"><Plus size={16}/> Create migration</button></div></form></div>}

const nav=[['dashboard','Dashboard',LayoutDashboard],['migrations','Migrations',BarChart3],['import','Import Panda',Upload],['watchtower','WatchTower',Network],['settings','Settings',Settings]]
export default function App(){
  const { user, getAccessToken, signOut }=useAuth()
  const repository=useMemo(()=>createMigrationRepository({getAccessToken}),[getAccessToken])
  const [data,setDataState]=useState([]),[page,setPage]=useState('dashboard'),[selected,setSelected]=useState(''),[modal,setModal]=useState(false),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let active=true;setLoading(true);repository.list(demo).then(rows=>{if(active)setDataState(rows)}).catch(err=>{if(active)setError(err.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[repository])
  const run=async work=>{setError('');try{return await work()}catch(err){setError(err.message);return null}}
  const open=id=>{setSelected(id);setPage('detail');setMobile(false)}
  const create=async m=>run(async()=>{const saved=await repository.create(m,data);setDataState(current=>[...current,saved]);await repository.appendActivity({migrationId:saved.id,action:'Migration created',summary:`Created migration for ${saved.partner}.`,actor:user});setModal(false);open(saved.id)})
  const save=async m=>run(async()=>{const before=data.find(x=>x.id===m.id), updated={...m,last:new Date().toISOString().slice(0,10)}, saved=await repository.update(updated,data);setDataState(current=>current.map(x=>x.id===saved.id?saved:x));const changes=[];if(before?.stage!==saved.stage)changes.push(`stage ${before?.stage || 'unset'} → ${saved.stage}`);if(before?.waitOn!==saved.waitOn)changes.push(`waiting on ${saved.waitOn}`);if(before?.owner!==saved.owner)changes.push(`owner ${saved.owner}`);await repository.appendActivity({migrationId:saved.id,action:'Migration updated',summary:changes.length?changes.join('; '):'Migration details updated.',actor:user})})
  const onImport=async(id,rows)=>run(async()=>{const migration=data.find(m=>m.id===id);if(!migration)throw Error('Select a migration before importing.');const priorByPanda=new Map((migration.accounts||[]).map(a=>[a.panda,a])),uniqueRows=rows.filter((row,index,all)=>all.findIndex(x=>x.panda===row.panda)===index).map(row=>({...row,wg:priorByPanda.get(row.panda)?.wg||row.wg}));const updated={...migration,stage:STAGES.indexOf(migration.stage)<2?'Account Preparation':migration.stage,last:new Date().toISOString().slice(0,10),accounts:uniqueRows},saved=await repository.update(updated,data);setDataState(current=>current.map(m=>m.id===id?saved:m));await repository.appendActivity({migrationId:id,action:'Panda customers imported',summary:`Imported ${uniqueRows.length} customer account${uniqueRows.length===1?'':'s'} from PPC.`,actor:user});open(id)})
  const current=data.find(m=>m.id===selected)
  let content=loading?<section className="panel"><h2>Loading migrations…</h2></section>:page==='migrations'?<Migrations data={data} open={open} newMigration={()=>setModal(true)}/>:page==='import'?<ImportPage data={data} onImport={onImport} newMigration={()=>setModal(true)}/>:page==='watchtower'?<WatchTower/>:page==='settings'?<div className="stack"><div className="heading"><div><small>APPLICATION CONFIGURATION</small><h1>Settings</h1></div></div><section className="panel"><h2>{isSharedDataMode?'Shared production data':'Demo data'}</h2><p>{isSharedDataMode?'Migrations and activity are stored in the configured SharePoint Lists and changes are attributed to the signed-in Microsoft user.':'This mode preserves the browser-only localStorage demo with fictional sample data.'}</p>{!isSharedDataMode&&<button className="secondary" onClick={()=>{repository.reset();setDataState(demo)}}>Reset demo data</button>}</section></div>:page==='detail'&&current?<Detail migration={current} save={save} back={()=>setPage('migrations')}/>:<Dashboard data={data} open={open} newMigration={()=>setModal(true)}/>
  const displayName=user?.name||'Demo User', initial=displayName.trim().charAt(0).toUpperCase()||'U'
  return <div className="shell"><aside className={mobile?'open':''}><div className="brand"><Logo/><b>MIGRATION <span>HUB</span></b></div><nav>{nav.map(([id,label,I])=><button key={id} className={(page===id||(id==='migrations'&&page==='detail'))?'active':''} onClick={()=>{setPage(id);setSelected('');setMobile(false)}}><I size={17}/>{label}</button>)}</nav><div className="by">BY <b>◈ dolos</b></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}<main><header><div><button className="mobile" onClick={()=>setMobile(true)}><Menu size={19}/></button><b>WATCHGUARD MIGRATION HUB</b><span>Operations & workflow tracker</span></div><div><em>{isSharedDataMode?'PILOT · SHAREPOINT':'MVP · LOCAL DATA'}</em><button className="bell"><Bell size={16}/></button><button className="user" onClick={()=>user?.username&&signOut()} title={user?.username?'Sign out':''}><i>{initial}</i>{displayName}<ChevronDown size={13}/></button></div></header><article>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}{content}</article></main>{modal&&<NewModal close={()=>setModal(false)} create={create}/>}</div>
}
